#!/usr/bin/env bash
#
# Installs and configures PostgreSQL for NimbusEye.
#
# Run once, with sudo:
#     sudo bash deploy/setup-postgres.sh
#
# What it does:
#   1. installs postgresql-16
#   2. starts the cluster (handles WSL, where systemd may not be running)
#   3. creates the nimbuseye database and two roles:
#        nimbuseye_migrator — owns the schema, used only by migrations
#        nimbuseye_app      — the application role; NOT the owner, so that
#                             row-level security actually applies to it
#   4. writes a password file readable only by the invoking user
#
# It is idempotent: running it again will not clobber an existing database.

set -euo pipefail

DB_NAME="${DB_NAME:-nimbuseye}"
# Detect what this release actually ships rather than pinning a version: Ubuntu
# 24.04 has 16, 26.04 has 18, and a hardcoded number fails on the wrong one.
PG_VERSION="${PG_VERSION:-}"
# Where the generated credentials land. The app reads its DSN from here.
TARGET_USER="${SUDO_USER:-$(id -un)}"
TARGET_HOME=$(getent passwd "$TARGET_USER" | cut -d: -f6)
ENV_FILE="${ENV_FILE:-$TARGET_HOME/.nimbuseye/db.env}"

if [ "$(id -u)" -ne 0 ]; then
  echo "This script needs root. Run: sudo bash $0" >&2
  exit 1
fi

export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
if [ -z "$PG_VERSION" ]; then
  PG_VERSION=$(apt-cache policy postgresql 2>/dev/null | awk '/Candidate:/ {print $2}' | grep -oE '^[0-9]+')
  [ -z "$PG_VERSION" ] && PG_VERSION=16
fi
echo "==> Installing PostgreSQL $PG_VERSION"
apt-get install -y -qq "postgresql-$PG_VERSION" postgresql-contrib >/dev/null
echo "    installed: $(psql --version)"

PGBIN="/usr/lib/postgresql/$PG_VERSION/bin"
PGDATA="/var/lib/postgresql/$PG_VERSION/main"

echo "==> Starting the cluster"
if pg_isready -q 2>/dev/null; then
  echo "    already accepting connections"
elif command -v systemctl >/dev/null && systemctl is-system-running --quiet 2>/dev/null; then
  systemctl enable --now "postgresql@$PG_VERSION-main"
  echo "    started via systemd"
else
  # WSL without systemd: pg_ctlcluster works where systemctl does not.
  pg_ctlcluster "$PG_VERSION" main start || true
  if ! pg_isready -q; then
    echo "    falling back to direct pg_ctl"
    su - postgres -c "$PGBIN/pg_ctl -D $PGDATA -l /var/log/postgresql/startup.log start" || true
  fi
  echo "    started via pg_ctlcluster"
fi

for _ in $(seq 1 20); do
  pg_isready -q && break
  sleep 1
done
if ! pg_isready -q; then
  echo "PostgreSQL did not come up. Check /var/log/postgresql/." >&2
  exit 1
fi

echo "==> Creating roles and database"
# Generated, not chosen: a password nobody types is a password nobody reuses.
APP_PW=$(head -c 32 /dev/urandom | base64 | tr -d '/+=' | head -c 32)
MIG_PW=$(head -c 32 /dev/urandom | base64 | tr -d '/+=' | head -c 32)

# `sudo -u postgres`, not `su - postgres`. A login shell prints the system MOTD,
# and that banner lands in stdout — which silently corrupts every
# `if [ -z "$(query)" ]` existence check in this script.
psql_q() { sudo -u postgres psql -v ON_ERROR_STOP=1 -qtAX -d postgres -c "$1"; }
psql_db() { sudo -u postgres psql -v ON_ERROR_STOP=1 -qtAX -d "$DB_NAME" -c "$1"; }

ensure_role() {
  local role="$1" pw="$2"
  if [ -z "$(psql_q "SELECT 1 FROM pg_roles WHERE rolname='$role'")" ]; then
    psql_q "CREATE ROLE $role LOGIN PASSWORD '$pw'" >/dev/null
    echo "    role $role created"
  else
    psql_q "ALTER ROLE $role PASSWORD '$pw'" >/dev/null
    echo "    role $role password rotated"
  fi
}

ensure_role nimbuseye_migrator "$MIG_PW"
ensure_role nimbuseye_app "$APP_PW"

# The app role must never be superuser or the schema owner: PostgreSQL exempts
# both from row-level security, which would silently disable tenant isolation.
psql_q "ALTER ROLE nimbuseye_app NOSUPERUSER NOCREATEDB NOCREATEROLE NOBYPASSRLS" >/dev/null

if [ -z "$(psql_q "SELECT 1 FROM pg_database WHERE datname='$DB_NAME'")" ]; then
  psql_q "CREATE DATABASE $DB_NAME OWNER nimbuseye_migrator" >/dev/null
  echo "    database $DB_NAME created"
else
  echo "    database $DB_NAME already exists, left alone"
fi

# Revoke the default public-schema rights every role otherwise inherits.
psql_db "REVOKE ALL ON SCHEMA public FROM PUBLIC" >/dev/null
psql_db "GRANT USAGE ON SCHEMA public TO nimbuseye_app" >/dev/null
psql_db "GRANT ALL ON SCHEMA public TO nimbuseye_migrator" >/dev/null
echo "    public schema locked down"

echo "==> Writing $ENV_FILE"
install -d -m 700 -o "$TARGET_USER" -g "$TARGET_USER" "$(dirname "$ENV_FILE")"
cat > "$ENV_FILE" <<EOF
# Generated by deploy/setup-postgres.sh on $(date -Iseconds)
# Application DSN — used by cmd/api. Least privilege, subject to row-level security.
NIMBUSEYE_DSN=postgres://nimbuseye_app:$APP_PW@127.0.0.1:5432/$DB_NAME?sslmode=disable
# Migration DSN — owns the schema. Used only by --migrate.
NIMBUSEYE_MIGRATE_DSN=postgres://nimbuseye_migrator:$MIG_PW@127.0.0.1:5432/$DB_NAME?sslmode=disable
EOF
chown "$TARGET_USER:$TARGET_USER" "$ENV_FILE"
chmod 600 "$ENV_FILE"

echo
echo "Done."
echo "  database : $DB_NAME"
echo "  roles    : nimbuseye_app (RLS applies), nimbuseye_migrator (schema owner)"
echo "  DSNs     : $ENV_FILE  (mode 600, owned by $TARGET_USER)"
echo
echo "Next, as $TARGET_USER:"
echo "  go run ./cmd/api --migrate"
